//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace brodersService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationHistory
    {
        public int ID { get; set; }
        public int FK_ApplicationID { get; set; }
        public int FK_StatusID { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
    }
}
