//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace brodersService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class broders_dbEntities : DbContext
    {
        public broders_dbEntities()
            : base("name=broders_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationHistory> ApplicationHistory { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<ApplicationStatus> ApplicationStatus { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfo { get; set; }
        public virtual DbSet<DigitalIdPropertyLinks> DigitalIdPropertyLinks { get; set; }
        public virtual DbSet<DigitalIds> DigitalIds { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<PropertyInfo> PropertyInfo { get; set; }
    }
}
