//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace brodersService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalIds
    {
        public DigitalIds()
        {
            this.CustomerInfo = new HashSet<CustomerInfo>();
            this.DigitalIdPropertyLinks = new HashSet<DigitalIdPropertyLinks>();
        }
    
        public int ID { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<CustomerInfo> CustomerInfo { get; set; }
        public virtual ICollection<DigitalIdPropertyLinks> DigitalIdPropertyLinks { get; set; }
    }
}
