//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace brodersService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalIdPropertyLinks
    {
        public int ID { get; set; }
        public int FK_PropertyId { get; set; }
        public int FK_DigitalId { get; set; }
    
        public virtual PropertyInfo PropertyInfo { get; set; }
        public virtual DigitalIds DigitalIds { get; set; }
    }
}
