//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace brodersService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyInfo
    {
        public PropertyInfo()
        {
            this.DigitalIdPropertyLinks = new HashSet<DigitalIdPropertyLinks>();
        }
    
        public int ID { get; set; }
        public decimal Amount { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Url { get; set; }
        public System.Data.Entity.Spatial.DbGeography GpsCoords { get; set; }
    
        public virtual ICollection<DigitalIdPropertyLinks> DigitalIdPropertyLinks { get; set; }
    }
}
